# The main config file for your Jekyll template

# Site settings
title: Nisha Makes Things               # used for the html title of every page
desc: >
  Nisha makes things

url: http://nishakm.github.io      # put your website hosting url here
baseurl: ''                 # the subpath of your site, e.g. /blog
permalink: /:year/:title/   # how should we display posts url

# Meta settings
email: nishakumarx@gmail.com
author: Nisha K.
github_username: nishakm

# Put your ga tracking code below
google_analytics: 'UA-XXXXXXXX-X'

# Pagination settings
paginate: 5                           # number of posts to show per page
paginate_path: "/page:num/"  # link scheme for articles, should be letf as is

# Navigation settings
# Used to define the navigation menu items
# > Title is the tile of the navigation item, url the url and desc is the tooltip
navigation:
  - title: Engineering
    url: /engineering/
    desc: Electronics + Code
  - title: Craft
    url: /craft/
    desc: Crochet and Stuff
  - title: Food
    url: /food/
    desc: Yum!
  - title: About Me
    url: /about/
    desc: Nisha who?

# Used by Jekyll to recognize what is a post and what is a page
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

# Markdown parser settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false          # you can change this if you feel like it
  parse_block_html: true    # allow parsing html inside markdown

# Build settings
include:
  - _pages                  # all your pages can be put inside pages (except articles)
exclude:
  - README.md
  - vendor
gems:
  - jekyll-paginate
